[build]
builder = "dockerfile"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && npx prisma db seed && node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
